Feature
AgazadeAV/andersen-trainee pull request #7
Opened 2024-11-20 19:38 UTC by AgazadeAV

2024-11-21 16:27 UTC, Alexmansar requested changes
@AgazadeAV Why all tests were removed?
you have several entities
create 1 interface with the base CRUD opearation, and create impl for each service and just use it)

2024-11-21 16:27 UTC, Alexmansar commented on hotel/src/main/java/com/andersenhotels/model/Hotel.java
>      }
a lot of logic in entitty class. use service for it

2024-11-23 18:14 UTC, Alexmansar commented
> Why all tests were removed?

@AgazadeAV Hi)) so, why all tests were removed?

2024-11-23 18:33 UTC, AgazadeAV commented
@Alexmansar, I'm rewriting them again, because all logic has been changed and I decided that it will be easier to write them again))
right now I'm writing tests))

2024-11-24 11:04 UTC, Alexmansar requested changes
@AgazadeAV Hi)) please, use annotation style when work with Mockito

2024-11-24 11:04 UTC, Alexmansar commented on hotel/src/test/java/com/andersenhotels/model/service/AbstractCrudServiceTest.java
> +        MockitoAnnotations.openMocks(this);
use annotation style please

2024-11-24 11:04 UTC, Alexmansar commented on hotel/src/test/java/com/andersenhotels/model/service/AbstractCrudServiceTest.java
> +        Mockito.reset(entityManager, transaction, entityManagerFactory);
static import

2024-11-24 11:04 UTC, Alexmansar commented on hotel/src/test/java/com/andersenhotels/model/service/AbstractCrudServiceTest.java
> +import static org.mockito.Mockito.*;
I mean you use it here, so in other places withou Mockito.

2024-11-24 11:04 UTC, Alexmansar commented on hotel/src/test/java/com/andersenhotels/model/service/GuestServiceTest.java
> +        guestService = spy(new GuestService());
same about annotations

2024-11-24 11:04 UTC, Alexmansar commented on hotel/src/test/java/com/andersenhotels/model/service/ReservationServiceTest.java
> +        apartment = mock(Apartment.class);
and here

2024-11-24 11:04 UTC, Alexmansar commented on hotel/src/test/java/com/andersenhotels/model/service/ReservationServiceTest.java
> +//    }
remove or use

2024-11-25 18:31 UTC, Alexmansar approved these changes

2024-11-25 19:24 UTC, merged